# Generated by Django 6.0.5 on 2026-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=50)),
                ('machine_name', models.CharField(max_length=100)),
                ('machine_type', models.CharField(choices=[('CNC', 'CNC'), ('Lathe', 'Lathe'), ('Conveyor', 'Conveyor'), ('Press', 'Press'), ('Packaging', 'Packaging')], default='CNC', max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('date_installed', models.DateField()),
            ],
        ),
    ]
