# Generated by Django 6.0.5 on 2026-05-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_photo',
            field=models.ImageField(blank=True, null=True, upload_to='machine_photos/'),
        ),
    ]
