# Generated by Django 6.0.5 on 2026-06-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchaserequest_eta_purchaserequest_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
