# Generated by Django 6.0.5 on 2026-06-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_alter_purchaserequest_estimated_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
