# Generated by Django 6.0.5 on 2026-05-28 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ticket_photos/')),
                ('purchasing_status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Ordered', 'Ordered'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=50)),
                ('maintenance_accepted', models.BooleanField(default=False)),
                ('maintenance_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
            ],
        ),
    ]
