# Generated by Django 6.0.5 on 2026-06-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='maintenance_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='materials_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='purchase_request_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sent_to_purchasing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='workflow_status',
            field=models.CharField(choices=[('MAINTENANCE', 'Waiting for Maintenance'), ('PURCHASING', 'Waiting for Purchasing'), ('APPROVAL', 'Waiting for Approval'), ('APPROVED', 'Approved for Purchase'), ('DELIVERED', 'Materials Delivered'), ('CLOSED', 'Closed')], default='MAINTENANCE', max_length=30),
        ),
    ]
