# Generated by Django 6.0.5 on 2026-06-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_materialrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sent_to_approval_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
